services:
  python-web:
    build: ./app1
    ports:
      - "5000:5000"
    restart: always
  
  oncall-apka:      # Musí být takto odsazené (2 mezery)
    build: ./oncall
    ports:
      - "5001:8000"
    restart: always # Doporučuji přidat i sem